### PR TITLE
updating sponsors and speakers

### PR DESCRIPTION
**Pull request by daudich**

### CODE REVIEW

**Comment by daudich** [comment]
Great. More conflicts!

**Comment by daudich** [comment]
@alexcoco Done!

**Comment by alexcoco** [comment]
I'll give this a more thorough look when I get home but it's looking good after a quick look.

**Comment by daudich** [comment]
Ok. I'm working on adding social media icons under the user profile. Please standby for more commits.

**Comment by daudich** [comment]
@alexcoco Done

**Comment by daudich** [comment]
@alexcoco If everything is okay, could you please merge this? Cheers!

**Comment by alexcoco** [comment]
I'll get to it later tonight

**Pull request merged**
